name: Build and Test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo REACT_APP_FIRESTORE_KEY=${{ secrets.REACT_APP_FIRESTORE_KEY }} >> .env
          echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
          echo REACT_APP_PROJECTID=${{ secrets.REACT_APP_PROJECTID }} >> .env
          echo REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
          echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
          echo REACT_APP_ENV=${{ secrets.REACT_APP_ENV }} >> .env
          cat .env
      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
